export const subjects: Record<string, string> = {
  "R&#39;Courses, Div Undergrad Ed": "UGRC",
  "Academic Resource Center": "ARC",
  "Actuarial Sciences": "BUAS",
  Anthropology: "ANTH",
  "Arabic Language": "ARBC",
  "Arabic Literatures and Culture": "ARLC",
  Art: "ART",
  "Art History": "AHS",
  "Asian Literature": "ALT",
  "Asian Studies": "AST",
  "Basic Writing": "BSWT",
  Biochemistry: "BCH",
  Bioengineering: "BIEN",
  Biology: "BIOL",
  "Biomedical Sciences": "BMSC",
  Biophysics: "BPHY",
  "Black Study": "BLKS",
  "Botany/Plant Science": "BPSC",
  Business: "BUS",
  "CHASS First Yr Experience Prog": "CHFY",
  Cahuilla: "CAH",
  "Cell Biology and Neuroscience": "CBNS",
  "Cell, Molecular, and Develpmnt": "CMDB",
  "Chemical Engineering": "CHE",
  "Chemical and Environmental Eng": "CEE",
  Chemistry: "CHEM",
  Chinese: "CHN",
  "Classical Studies": "CLA",
  "Comparative Ancient Civilizatn": "CPAC",
  "Comparative Literature": "CPLT",
  "Computer Science": "CS",
  "Creative Writing": "CRWT",
  "Crwt Wrt &amp; Wrt for Perf Arts": "CWPA",
  Dance: "DNCE",
  "Div of Undergraduate Education": "UGRD",
  Economics: "ECON",
  Education: "EDUC",
  "Electrical Engineering": "EE",
  Engineering: "ENGR",
  English: "ENGL",
  Entomology: "ENTM",
  "Environmental Engineering": "ENEN",
  "Environmental Sciences": "ENSC",
  "Environmental Toxicology": "ENTX",
  "Ethnic Studies": "ETST",
  "European Culture": "EUR",
  "Evoltn, Ecolgy, &amp; Orgnsml Bio": "EEOB",
  Filipino: "FIL",
  French: "FREN",
  "Gender and Sexuality Studies": "GSST",
  Genetics: "GEN",
  "Genetics and Biotechnology": "GNBT",
  Geosciences: "GEO",
  German: "GER",
  "Global Studies": "GBST",
  "Graduate Division": "GDIV",
  Greek: "GRK",
  "Highlander Early Start Academy": "HESA",
  History: "HIST",
  "History of Europe": "HISE",
  "History of the Americas": "HISA",
  Honors: "HNPG",
  "Humanities, Arts and Soc Sci": "HASS",
  Italian: "ITAL",
  Japanese: "JPN",
  Korean: "KOR",
  "Labor Studies": "LABR",
  Latin: "LATN",
  "Latin American Studies": "LNST",
  "Law &amp; Society": "LWSO",
  "Lesbian, Gay, Bisexual Studies": "LGBS",
  "Liberal Studies Program": "LBST",
  Linguistics: "LING",
  "Literatures &amp; Languages": "LTLG",
  "Low Res-Crwt Wrt&amp;Wrt-Perf Arts": "CWLR",
  Management: "MGT",
  "Materials Sci and Engineering": "MSE",
  Mathematics: "MATH",
  "Mechanical Engineering": "ME",
  "Media and Cultural Studies": "MCS",
  "Medical and Health Humanities": "MHHS",
  Microbiology: "MCBL",
  "Middle East and Islamic Stds": "MEIS",
  "Molecular, Cell &amp; Systems Biol": "MCSB",
  Music: "MUS",
  "Natural &amp;Agricultural Sciences": "NASC",
  Nematology: "NEM",
  Neuroscience: "NRSC",
  "Peace and Conflict Studies": "PCST",
  Philosophy: "PHIL",
  Physics: "PHYS",
  "Plant Pathology": "PLPA",
  "Political Science": "POSC",
  Portuguese: "PORT",
  Psychology: "PSYC",
  "Public Health-Social Medicine": "PBHL",
  "Public Policy": "PBPL",
  Recreation: "REC",
  "Religious Studies": "RLST",
  "Russian Studies": "RUSN",
  "School of Medicine": "MDCL",
  "Society, Envmnt, Health Equity": "SEHE",
  Sociology: "SOC",
  "Soil and Water Science": "SWSC",
  "Southeast Asian Studies": "SEAS",
  Spanish: "SPN",
  "SpecltveFic &amp; Cultures Science": "SFCS",
  Statistics: "STAT",
  "Theater, Film &amp; Digital Prod": "TFDP",
  Theatre: "THEA",
  "Tri-Campus Classic": "TCMP",
  "University Writing Program": "WRIT",
  "Urban Studies": "URST",
  Vietnamese: "VNM",
  "Women s Studies": "WMST",
  "World Literature": "WRLT",
};
